In [1]:
import numpy as np

In [2]:
a =np.array([2,11,3,5,10,4,1])

In [3]:
np.average(a)

5.142857142857143

In [4]:
np.sort(a)

array([ 1,  2,  3,  4,  5, 10, 11])

In [5]:
np.min(a)

1

In [6]:
np.max(a)

11

In [7]:
b=np.array([2,11,3,5,10,0,0])

In [8]:
np.nonzero(b)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [9]:
c =np.array([[2,3],[1,3],[4,5]])

In [10]:
c.shape

(3, 2)

## Creating a Matrix

In [11]:
matrix= np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Selecting Eements From Array 


In [12]:
array = np.array([1,2,3,4,5,6,7,8,9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array[0]

1

In [14]:
array[2]

3

In [15]:
array[-1]

9

In [16]:
array[-3]

7

In [17]:
array[3:6] 

array([4, 5, 6])

In [18]:
array[:] #all elements 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
matrix[:3,:2] # [rows,columns]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [20]:
matrix[:2,:2]

array([[1, 2],
       [4, 5]])

In [21]:
matrix[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [22]:
matrix[0:3:2,:] 

array([[1, 2, 3],
       [7, 8, 9]])

In [23]:
matrix[0:3:1,0:3:2]

array([[1, 3],
       [4, 6],
       [7, 9]])

## Diagonal Selecting

In [24]:
matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
matrix.diagonal()

array([1, 5, 9])

In [26]:
matrix.diagonal(offset=1)

array([2, 6])

In [27]:
matrix.diagonal(offset=2)

array([3])

In [28]:
matrix.diagonal(offset=-1)

array([4, 8])

In [29]:
matrix.trace() # Return the sum along diagonals of the array

15

In [30]:
matrix.trace(offset=1) # The sum of diagonal with its given offset

8

In [31]:
matrix.trace(offset=-1) 

12

## Describing a Matrix

In [32]:
matrix.shape

(3, 3)

In [33]:
matrix.size

9

In [34]:
matrix.ndim #number of dimensions of an array

2

In [35]:
matrix.max() # or np.max(matrix)

9

In [36]:
matrix.min() # or np.min(matrix)

1

In [37]:
matrix.max(axis=1) #column

array([3, 6, 9])

In [38]:
matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
matrix.max(axis=0) #row

array([7, 8, 9])

In [40]:
matrix.max(axis=1) #column

array([3, 6, 9])

In [41]:
matrix.max(axis=1)[0] # 1st column 0th row

3

## Mean, Variance, Standard Deviation

In [42]:
matrix.mean()

5.0

In [43]:
matrix.var()

6.666666666666667

In [44]:
matrix.std()

2.581988897471611

## Reshaping

In [45]:
matrix.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
matrix.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## Transpose Matrix

In [47]:
matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Arithmetic Operators with Two Matrix

In [49]:
matrix_1= matrix.T
matrix_1

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [50]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
matrix*matrix_1

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [53]:
matrix+matrix_1

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [54]:
matrix-matrix_1

array([[ 0, -2, -4],
       [ 2,  0, -2],
       [ 4,  2,  0]])

In [55]:
matrix/matrix_1

array([[1.        , 0.5       , 0.42857143],
       [2.        , 1.        , 0.75      ],
       [2.33333333, 1.33333333, 1.        ]])

In [62]:
np.random.randint(0,100,10) # random 10 values in 0 to 100

array([ 1, 62, 88, 99, 37, 46, 75, 85, 39, 59])